apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: svc-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 38123
  selector:
    app: nginx
  type: LoadBalancer
