---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/hostpath-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/hostpath-provisioner