---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service-np
  labels:
    app: pratica4
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: pratica4
    tier: FE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: pratica4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pratica4
  template:
    metadata:
      labels:
        app: pratica4
        tier: FE
    spec:
      containers:
      - image: drupal:latest
        name: drupal
        ports:
        - containerPort: 30080
          name: drupal
        volumeMounts:
        - name: drupal-ps
          mountPath: /var/www/html/modules
          subPath: modules
        - name: drupal-ps
          mountPath: /var/www/html/profiles
          subPath: profiles
        - name: drupal-ps
          mountPath: /var/www/html/themes
          subPath: themes
      volumes:
      - name: drupal-ps
        persistentVolumeClaim:
          claimName: drupal-pvc