---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-ci
  labels:
    app: pratica4
spec:
  ports:
    - port: 5432
  selector:
    app: pratica4
    tier: DB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-postgre
  labels:
    app: pratica4
spec:
  selector:
    matchLabels:
      app: pratica4
  replicas: 1
  template:
    metadata:
      labels:
        app: pratica4
        tier: DB
    spec:
      containers:
      - image: postgres:latest
        name: postgresql
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: db_user
        - name: POSTGRES_DB
          value: drupal
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: db_pwd
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgre-ps
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgre-ps
        persistentVolumeClaim:
          claimName: postgresql-pvc