version: "3"
services:
  node:
    build: .
    container_name: node_build_compose
    #command: nodemon index.js
    ports:
      - 3000:8080
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules/
    environment:
      - NAME= Docker Compose