apiVersion: v1
kind: Pod
metadata:
  name: kuard-secrets
spec:
  containers:
    - name: test-container
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      command:
        - "/kuard"
        - "$(USERNAME)"
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_pwd
  restartPolicy: Never
